---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  DB_URI: cG9zdGdyZXNxbDovL3Bvc3RncmVzOlAwc3RncjNzQHBvc3RncmVzLXN2Yy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZW52aXJvbm1lbnRfYWlycV9tZWFzdXJhbmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: measurement-app
  labels:
    app: measurement-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: measurement-app
  template:
    metadata:
      labels:
        app: measurement-app
    spec:
      containers:
      - name: measurement-app
        image: pablowilliams87/measurement-app:1.2
        ports:
        - containerPort: 5000
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_URI
       
---
apiVersion: v1 
kind: Service
metadata: 
  name: measurement-app-svc
  labels:
    app: measurement-app
spec: 
  selector: 
    app: measurement-app 
  type: ClusterIP 
  ports: 
  - name: measurement-app
    port: 5000
    targetPort: 5000
    protocol: TCP
